### ISSUE TITLE
Missing fishfile

### ISSUE THREAD

**Issue by Markcial** [reitzig/sdkman-for-fish#11]
I see that on your fish plugin you use the `edc/bass`  dependency. For that kind of deps use the [`fishfile`](https://github.com/fisherman/fisherman#what-is-a-fishfile-and-how-do-i-use-it) format.

Or simply `echo "edc/bass" >> fishfile`.

**Comment by reitzig** [comment]
I don't think I do? What am I missing?

**Comment by Markcial** [comment]
Sorry, i don't know if i mistakingly saw it on an older version of master or i am plain wrong, just forget this issue.
