### ISSUE TITLE
Switch development to the official fisherman plugin

### ISSUE THREAD

**Issue by Markcial** [reitzig/sdkman-for-fish#12]
I added you as a collaborator to the fisherman group inside the sdkman plugin, feel free to switch your work there.

Also if you need help or add more collaborators ping any member of the core group or me

https://github.com/fisherman/sdkman

**Comment by reitzig** [comment]
Could you please shortly explain what that would entail and what the benefits are? Right now, CI is set up for this repo, I have issues here, etc...

If I deem a move (for myself) appropriate, I think moving the repo as-is over to a new owner would be better than creating a clone (that's not even marked as a fork).

**Comment by Markcial** [comment]
I copied the repo so you can do development there as a choice, if you still want to maintain the repo under your username is ok. To transfer ownership is possible if you find any of the core members able to do so. Just chime in in the slack channel and check for volunteers.

Whichever option you choose, to maintain the repo by your own, maintain it on fisherman or find a new owner is fine.

**Comment by reitzig** [comment]
I guess I don't understand where you're coming from. Are you trying to consolidate all fisherman-style fish repos under one organization? (Why?) Are you offering a shared place to maintenance can be more easily transferred whenever a maintainer drops out for any reason? 

I've always viewed it as an advantage of Github that it basically doesn't matter which account owns a repo, for most purposes -- everybody can get involved everywhere. Right now, I don't see an advantage of migrating; having two repos around might be confusing (you might have asked _before_ creating it. ;) ).

Is there any precedence either way?

**Comment by Markcial** [comment]
You have admin right on that repository, if you want to have the plugin under your username, just erase it. Just gave you the choice to belong to the fisherman group as owner of one of the plugins. But its not a cult, you are able to opt out, its fine

**Comment by reitzig** [comment]
I think I understand now, thanks.

I've decided to leave the repo in my own account for now. Should the situation change and I would like to have the project under the umbrella of fisherman and/or hand development over to another party, I'll know whom to call. :)

FWIW:

> Delete this repository
> Organization members cannot delete repositories.

I archived it for the time being so there is no confusion.

**Comment by reitzig** [comment]
@Markcial Please delete `fisherman/sdkman`. It seems to take precedence over the [index](https://github.com/fisherman/index/pull/102):

```
$ fisher i sdkman
Installing 1 plugin/s
OK Fetch sdkman github.com/fisherman/sdkman
Done in 1s 594ms
```
