### ISSUE TITLE
Error on MacOS 10.14.6 stat illegal option -c

### ISSUE THREAD

**Issue by nbu** [reitzig/sdkman-for-fish#30]
https://github.com/reitzig/sdkman-for-fish/blob/d811a8ddc2dde1cd2518c924430a272c37909bc7/conf.d/sdk.fish#L80

On MacOS 10.14.6 this command must be used:
```
stat -f "%u"
```

**Comment by reitzig** [comment]
Well that sucks for macOS, doesn't it? ;P

In seriousness: as discussed [here](https://github.com/reitzig/sdkman-for-fish/pull/28), another fix has been implemented on branch [`macos-compat`](https://github.com/reitzig/sdkman-for-fish/tree/macos-compat). There's some work left to do for #29 before I can merge that one into `master`, but I think you can install the branch through fisher.
