### ISSUE TITLE
Error with usage of `stat` in `sdk.fish` when running `fisher`

### ISSUE THREAD

**Issue by krishnan-mani** [reitzig/sdkman-for-fish#31]
(_Update_: i now see that this [issue](https://github.com/reitzig/sdkman-for-fish/issues/29) already reports the problem and there are attempts underway to fix it. Feel free to close as subsumed under the earlier issue)

I see the following error (appears to come from `sdk.fish`) when running `fisher`

```
...
linking ~/.config/fish/conf.d/sdk.fish
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
updated 1 package in 1.20s
...
```

I am on macOS Mojave, version 10.14.6
```
$ uname -a
Darwin ELSOXFM-189408 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

$ fish --version
fish, version 3.0.2

```

**Comment by reitzig** [comment]
This is a known issue; cf #29.

A fix for this particular issue is already available on branch `macos-compat` which, I think, you can have fisher install as well.
