### ISSUE TITLE
Does not install.. 

### ISSUE THREAD

**Issue by inktomi** [reitzig/sdkman-for-fish#32]
When I attempt to install the sdkman-for-fish, I get.. 

>fetching https://codeload.github.com/reitzig/sdkman-for-fish/tar.gz/master
>fisher: cannot add github.com/reitzig/sdkman-for-fish -- is this a valid package?
>done in 2.23s

**Comment by reitzig** [comment]
Which command did you run there?

What's the output of the following?

```
fish --version
fisher --version
```

For me:

```
$ fisher --version
fisher version 3.2.9 ~/.config/fish/functions/fisher.fish
$ fish --version
fish, version 2.7.1
$ fisher
fetching https://codeload.github.com/reitzig/sdkman-for-fish/tar.gz/master
linking ~/.config/fish/functions/sdk.fish
linking ~/.config/fish/completions/sdk.fish
linking ~/.config/fish/conf.d/sdk.fish
updated 1 package in 0.79s
```

**Comment by inktomi** [comment]
Thanks! Here's the output: 

fish - 3.0.2
fisher - 3.2.10  ~/.config/fish/functions/fisher.fish

$cat ~/.config/fish/fishfile                                                                                                                                     
<empty file>

**Comment by reitzig** [comment]
> Which command did you run there?

Can you answer this, please? So far, I don't have enough information to try and reproduce.

In the meantime, can you please add that line to `fishfile` and run `fisher`?

**Comment by reitzig** [comment]
Can't reproduce over here. Using the installation instructions from the fisher and sdkman-for-fish repos, respectively:

```bash
r> sudo useradd -m foo
r> sudo su foo
f$ fish
f> curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
f> fisher add reitzig/sdkman-for-fish
created new fishfile in ~/.config/fish/fishfile
fetching https://codeload.github.com/reitzig/sdkman-for-fish/tar.gz/master
linking ~/.config/fish/functions/sdk.fish
linking ~/.config/fish/completions/sdk.fish
linking ~/.config/fish/conf.d/sdk.fish
added 1 package in 0.57s
f> sdk version
You don't seem to have SDKMAN! installed. Install now? [y/N] y
<snip>
All done!
Please open a new terminal/shell to load SDKMAN!
f> exit
f$ fish
f> sdk version
<snip>
SDKMAN 5.7.4+362
```

Seems to work as intended. That's on Ubuntu 18.04, with the versions given above.
