### ISSUE TITLE
Account for SDKMAN! being installed at custom path

### ISSUE THREAD

**Issue by avierr** [reitzig/sdkman-for-fish#34]
I usually have sdkman installer in /Users/Shared/sdkman directory so that two user can share the same sdkman instance.

I only have to set the sdkman path in my profile/rc file per user.

but seems like variable is hardcoded, https://github.com/reitzig/sdkman-for-fish/blob/c9fd8d58f2972c8664db6645ea37a3e35f2f5afb/conf.d/sdk.fish#L10

**Comment by reitzig** [comment]
You mean we should use `SDKMAN_DIR` instead? That makes sense to me, but I'd have to look at it more closely to not break the case where sdkman-for-fish installs sdkman.

**Comment by tmysik** [comment]
I just needed to workaround this by setting `set -g __fish_sdkman_init "/my/path/to/sdkman/bin/sdkman-init.sh"` in `~/.config/fish/config.fish`. Seems to be working fine.

_Note:_ I have installed SDKMAN! before sdkman-for-fish (in my custom directory) and it wanted me to download and install it again.

**Comment by reitzig** [comment]
Thanks! I figured it should be this simple, but I'll have to figure out how to handle 

 * not knowing `SDKMAN_DIR` without running it first (critical), and
 * installing it to a custom location (nice to have).

Maybe it'll have to be an (optional) setting with `HOME` as the default, but I would _prefer_ to have an automatism.

**Comment by tmysik** [comment]
@reitzig Maybe it could be interactive? Now, you are checking some variable and do installation if not set. What if you asked user what to do, whether SDKMAN! was already installed, etc. if such a variable is not set?

**Comment by reitzig** [comment]
It'll be like this: If `SDKMAN_DIR` is set, we will respect its value.

That is, if you have a custom installation, add

```
set -g __sdkman_custom_dir /your/path
```

to `.config/fish/conf.d/config_sdk.fish`.

cf. [corner_cases.feature#14](https://github.com/reitzig/sdkman-for-fish/blob/4c15f15ced5a67e00b161b2a5e83df7d660405d3/test/features/corner_cases.feature#L14)

Sorry for the long wait, but it's done now! 🙃
