### ISSUE TITLE
[Bug] Cannt find SDKMAN! for vscode terminal, but work for Windows Terminal.

### ISSUE THREAD

**Issue by 1216892614** [reitzig/sdkman-for-fish#47]
Somehow when I type `sdk` in vscode terminal, it always print:

- `You don't seem to have SDKMAN! installed. Install now? [y/N]`

even after I set `__sdkman_custom_dir` in my fish config. And, when I type `y`, I can see:

- `You already have SDKMAN installed.`

but it's not work. `You don't seem to have SDKMAN!...` come again when I try `sdk` after.

What's even stranger is this things only happen on my vscode terminal, I can use `sdk` in my Windows Terminal.

## Environment

- Windows 11
- WSL version: 2.1.0.0, Ubuntu 20 LTS
- VS Code 1.87.2
- fish version 3.3.1

I looked at the vscode extensions and only the git extension contributed to the environment variables

**Comment by 1216892614** [comment]
![image](https://github.com/reitzig/sdkman-for-fish/assets/54391927/cf5ae1c0-96a2-4a1c-8e45-c2c6a892a898)
![image](https://github.com/reitzig/sdkman-for-fish/assets/54391927/52194f41-794b-4971-9aaa-df4a97a8dd88)

**Comment by reitzig** [comment]
There seems to be an issue with VS Code and fish; if VS Code does not load your fish config, there's not a whole lot we can do on our end.

ref: https://stackoverflow.com/q/76627370  

Also note that we test neither WSL2 nor your fish version, nor can we support either. I will happily review PRs with tests and necessary changes to make the integration work better in more setups, though!
